## Numpy Arrays

In [332]:
import numpy as np

## Creating Arrays

In [333]:
data = [1, 2, 3, 4]
first_array = np.array(data)
first_array

array([1, 2, 3, 4])

In [334]:
data = [[1, 2, 3],
        [4, 5, 6], 
        [7, 8, 9]]
my_array = np.array(data)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [335]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [336]:
np.zeros(3)

array([0., 0., 0.])

## Dimensions and Shape

In [337]:
oned = np.arange(21)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [338]:
oned.shape

(21,)

In [339]:
oned.ndim

1

In [340]:
oned.size

21

In [341]:
list_o_list = [[1,2,3], [4,5,6], [7,8,9]]
twod = np.array(list_o_list)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [342]:
twod.ndim

2

In [343]:
twod.size

9

In [344]:
twod.shape

(3, 3)

In [345]:
oned = np.arange(12)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [346]:
twod = oned.reshape(3, 4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [347]:
twod.shape

(3, 4)

In [348]:
twod.ndim

2

In [349]:
oned = np.arange(12)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [350]:
twod = oned.reshape(3,4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [351]:
twod.shape

(3, 4)

In [352]:
twod.ndim

2

In [353]:
twod.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [ ]:
twod.reshape(2,2,3)    ##3 dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## Setting Data Type

In [361]:
darray = np.arange(150, dtype=np.int8)
print(darray)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127 -128 -127 -126 -125 -124 -123 -122 -121 -120 -119 -118 -117
 -116 -115 -114 -113 -112 -111 -110 -109 -108 -107]


In [362]:
darray.dtype

dtype('int8')

In [358]:
darray.nbytes

100

In [ ]:
darray[12] = 'a'  ## So, let's try adding a string to this array. That is of type integer eight, or eight bit integer. See, you cannot add a string.

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
darray[12] = 0.4  ## But the more misleading part, is that if you add, say a floating point decimal to our array and then check it. 
                  ## We see that what it's done is stripped off anything to the right of the decimal point.
                  ## So, keep in mind if you're setting the data types on your array, to be aware of your expectations of the data you're going to be putting.


In [365]:
darray[12]

0

## Broadcasting

In [367]:
A1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [368]:
A1.shape

(3, 3)

In [369]:
A2 = np.array([[1,1,1],
              [1,1,1],
              [1,1,1]])

In [377]:
A1 + A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [378]:
A1 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [384]:
A3 = np.array([1,1,1])
A3

array([1, 1, 1])

In [383]:
A3.shape

(3,)

In [ ]:
A4 = np.arange(10).reshape(2,1,5)      ## 2 number of blocks, 1 number of rows in each block, 5 number of columns in each row
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [376]:
A5 = np.arange(14).reshape(2,7,1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [387]:
A6 = A4 + A5
A6
A6.shape

(2, 7, 5)

## Matrix Operations

In [388]:
M1 = np.arange(9).reshape(3,3)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [389]:
M2 = np.arange(2, 11).reshape(3,3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [390]:
M1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [391]:
M1.diagonal()

array([0, 4, 8])

In [393]:
result = M1 @ M2     ##matrix multiplication
print(result)

[[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
